GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "abc",
    "number": "4834848"
}

###
DELETE  http://localhost:3001/api/persons/670144d5c69579013de0dc24
